### ISSUE TITLE
No mousepointer on buttons

### ISSUE THREAD

**Issue by pilz** [ploneintranet/ploneintranet.prototype#109]
multiple click actions missing mousepointer actions
add document, add folder, etc

**Comment by cornae** [comment]
Please explain.

**Comment by pilz** [comment]
@maartenkling can you provide some details?

**Comment by maartenkling** [comment]
Its starts on frontpage and continues everywhere

prototype.ploneintranet.net Move your mouse to the LOGIN button, and you dont see a mousepointer

**Comment by maartenkling** [comment]
@pilz @cornae ^^

**Comment by maartenkling** [comment]
on dashboard on all dropdown actions, the edit dashboard link, the right top notification actions etc
in workspaces on add document, add folder,

**Comment by pilz** [comment]
When I look at my desktop applications, my mousepointer doesn't change either. This could be a website thing and as we are building an application, that could be a different domain.

**Comment by cornae** [comment]
You make it sound like your pointer/cursor disappear on certain button, but do you mean that you expect the default cursor to change into a hand cursor, like it would with links on websites? If that's what you mean, then @pilz's answer is also my answer.

**Comment by maartenkling** [comment]
Yes i expect a hand cursor when possible to click. We are still making a application for web?

**Comment by cornae** [comment]
The technology is not relevant, it's the nature of the product that makes the difference. But even so, In native web technology and common design standards, on a button there's no hand cursor. Try to build a simple webform with a submit button without CSS. You won't get a hand cursor on any button, radio button, checkbox or other element where it's possible to click.

Some designers use CSS to do it, but it's against common guidelines. Also, if your design depends on cursor changes or roll overs to convince the user that something is an active area, you will really have a problem on touch devices.

**Comment by maartenkling** [comment]
http://prototype.ploneintranet.net/dashboard.html?__ac_name=&__ac_password= 
Edit Dashboard is a link, i expect a hand cursor on a link? Correct?

Does our customer expect internet behaviour buttons having a pointer or not is the relevant question i think. And in my opinion all buttons should have one. Just like here on github

**Comment by cornae** [comment]
Edit dashboard is an icon in the making. It will be a circle with a pencil icon in it so there you're looking at something unfinished. It currently looks neither like a link, nor like a button. 

Some customers might expect, others not. More relevant than what they expect is the question can they operate the application and does the cursor help or hinder there? As said before, if they can't recognise a button as a being a button without a hand cursor, you're in deep trouble on touch devices. So why do you need it anyway?

**Comment by maartenkling** [comment]
cant answer that question due to mobile version not working  https://github.com/ploneintranet/ploneintranet.prototype/issues/110

**Comment by pilz** [comment]
I would see that as a theoretical question as you don't have mouse pointers on mobile.

**Comment by cornae** [comment]
Don't confuse touch and mobile @maartenkling. They are different dimensions. Apart from that, surely you have enough capacity of imagination to answer that question even without any application at hand?

I found you an example of a text editor:

![image](https://cloud.githubusercontent.com/assets/738601/8617622/dad9865c-2705-11e5-85e6-b68005e94a62.png)

It come from Google. Not that it's right because it come from Google, but it's something that's undisputedly an application and not a website. You said:

> i expect a hand cursor when possible to click

It's possible to click on the buttons on the toolbar. Would you expect a hand cursor there? Wouldn't it be strange to have one there, but on a similar toolbar in Microsoft word you would have a regular cursor. Just because it's written in C and not HTML? I don't think the user cares about the underlaying technology. It's just an application because it looks enough like one.

Following your claim that everything clickable should generate a hand cursor would also mean the scroll bars would change the cursor, radio buttons would. In an application where merely any element has a function and is clickable, it would kind of defeat the purpose of cursor change if they change to a mouse pointer on almost everything.

**Comment by maartenkling** [comment]
ill stop this discussion fine by me

**Comment by cornae** [comment]
I'm happy that I could provide some insight. Please let me know if there's anything else not clear.
