### ISSUE TITLE
workflow transitions are broken

### ISSUE THREAD

**Issue by gyst** [ploneintranet/ploneintranet.prototype#32]
Multiple workflow changes on the same page without a reload breaks. See https://github.com/ploneintranet/ploneintranet/pull/173.

This is no longer a release blocker for Mercury - we'll ship with single transitions working and double transitions borked.

Related is the issue #30 where Plone has "transitions" towards a target state, not the target state itself as label on the transition. We need to discuss how we can gracefully handle that.

**Comment by cornae** [comment]
This has already been solved and build with a state model as opposed to a transition model in Star. Perhaps check with @pilz if there's something re-usable there. 

If it turns out to be hard still to follow this, then I could look into designing an alternative interaction model that's transition driven. It will be a few hours more work for me on the front end.
